apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-photos-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "图库"
    rbac.authorization.halo.run/ui-permissions: '["plugin:photos:view"]'
    rbac.authorization.halo.run/display-name: "图库查看"
rules:
  - apiGroups: [ "core.halo.run", "console.api.photo.halo.run"]
    resources: [ "photos", "photogroups" ]
    verbs: [ "get", "list" ]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-photos-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: '["role-template-photos-view"]'
    rbac.authorization.halo.run/ui-permissions: '["plugin:photos:manage"]'
    rbac.authorization.halo.run/module: "图库"
    rbac.authorization.halo.run/display-name: "图库管理"
rules:
  - apiGroups: [ "core.halo.run", "console.api.photo.halo.run"]
    resources: [ "photos", "photogroups" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]