apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-photos-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: text
          label: 页面标题
          name: title
          validation: required
          value: "图库"
        - $formkit: text
          label: 相册列表显示条数
          name: pageSize
          validation: required|Number
          value: 20
        - $formkit: attachmentPolicySelect
          label: 附件存储策略
          name: policyName
          validation: required
          help: 用于图库上传图片的存储策略
        - $formkit: attachmentGroupSelect
          label: 附件分组
          name: groupName
          help: 图库上传的图片将归入此附件分组